name: Build APK from WebApp
on:
  repository_dispatch:
    types: [build-app]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # On crée le fichier de config manuellement pour éviter les erreurs de détection automatique
          bubblewrap init --url=${{ github.event.client_payload.url }} --name="${{ github.event.client_payload.name }}" --no-prompt
          
          # On lance le build en acceptant tout
          yes | bubblewrap build --skipSigning
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: App-Release
          path: ./*.apk
