name: Build APK from WebApp
on:
  repository_dispatch:
    types: [build-app]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Bubblewrap
        run: npm install -g @bubblewrap/cli

      - name: Build APK
        run: |
          # 1. Configuration forcée de Bubblewrap (évite les questions)
          mkdir -p ~/.bubblewrap
          echo "{\"jdkPath\":\"${JAVA_HOME}\",\"androidSdkPath\":\"/usr/local/lib/android/sdk\"}" > ~/.bubblewrap/config.json
          
          # 2. Initialisation (directement à la racine pour éviter les erreurs de dossier)
          bubblewrap init --url=${{ github.event.client_payload.url }} --name="${{ github.event.client_payload.name }}" --no-prompt
          
          # 3. Compilation
          # On accepte tout et on affiche les erreurs s'il y en a
          yes | bubblewrap build --skipSigning
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Mon-APK-Genere
          path: "*.apk"
